Rugby
IlliaNebrat/Nebrat_JavaBase_1809 pull request #1
Opened 2023-10-12 12:58 UTC by IlliaNebrat

Add class Rugby to main

2023-10-12 14:45 UTC, JIeIIIa requested changes

2023-10-12 14:45 UTC, JIeIIIa commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        int[] team1Ages = new int[25];
Вже неоднарозово було про назви змінних, які відрізняються однією цифрою десь в середині. Так краще не робити. `firstTeamAges/secondTeamAges`, `redTeamAges/blueTeamAges` тощо. Це стосується і решти подібних змінних

2023-10-12 14:45 UTC, JIeIIIa commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        for (int i = 0; i < 25; i++) {
Чим даний цикл принципово відрізняється від попереднього? Я казав, що замість того щоб копіювати код його потрібно виносити в окремі методи і перевикористовувати. Подумай над відмінностями, які можна винести в параметри методу і зроби окремий метод. Також метод має робити щось одне, але добре. У тебе цикл зараз і заповнює, і виводить значення.

2023-10-12 14:45 UTC, JIeIIIa commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        double team1AverageAge = (double) team1TotalAge / 25;
Ти ж ділиш на довжину масива. У масива є вбудована змінна для цього...

2023-10-16 12:16 UTC, IlliaNebrat commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        int[] team1Ages = new int[25];
Виправлено

2023-10-16 12:17 UTC, IlliaNebrat commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        double team1AverageAge = (double) team1TotalAge / 25;
Виправлено

2023-10-16 12:17 UTC, IlliaNebrat commented on src/illia/nebrat/homework/rugby/Rugby.java
> +        for (int i = 0; i < 25; i++) {
Виправлено, здається)

2023-10-19 12:17 UTC, merged